additional_samples = [     
    {'word': 'salty', 'entity': 'flavor'},
    {'word': 'bitterness', 'entity': 'flavor'},
    {'word': 'not bitter', 'entity': 'flavor'},
    {'word': 'sweet', 'entity': 'flavor'},
    {'word': 'astringent', 'entity': 'flavor'},
    {'word': 'strawberry flavor', 'entity': 'flavor'},
    {'word': 'wheat fragrance', 'entity': 'flavor'},
    {'word': 'autumn fragrance', 'entity': 'flavor'},
    {'word': 'milk flavor', 'entity': 'flavor'},
    {'word': 'caramel', 'entity': 'flavor'},
    {'word': 'vanilla', 'entity': 'flavor'},
    {'word': 'sour', 'entity': 'flavor'},
    {'word': 'buttery', 'entity': 'flavor'},
    {'word': 'floral', 'entity': 'flavor'},
    {'word': 'fruity', 'entity': 'flavor'},
    {'word': 'aromatic', 'entity': 'flavor'},
    {'word': 'citrus', 'entity': 'flavor'},
    {'word': 'vegetarian', 'entity': 'persona'},
    {'word': 'mom', 'entity': 'persona'},
    {'word': 'pregnant woman', 'entity': 'persona'},
    {'word': 'allergy sufferer', 'entity': 'persona'},
    {'word': 'alcoholic', 'entity': 'persona'},
    {'word': 'single mother', 'entity': 'persona'},
    {'word': 'vegan', 'entity': 'persona'},
    {'word': 'cat lover', 'entity': 'persona'},
    {'word': 'dog lover', 'entity': 'persona'},
    {'word': 'book lover', 'entity': 'persona'},
    {'word': 'college student', 'entity': 'persona'},
    {'word': 'social worker', 'entity': 'persona'},
    {'word': 'animal lover', 'entity': 'persona'},
    {'word': 'mother', 'entity': 'persona'},
    {'word': 'proud dad', 'entity': 'persona'},
    {'word': 'traveller', 'entity': 'persona'},
    {'word': 'stay at home mom', 'entity': 'persona'},
    {'word': 'teacher', 'entity': 'persona'},
    {'word': 'health practitioner', 'entity': 'persona'},
    {'word': 'office worker', 'entity': 'persona'},
    {'word': 'an old woman', 'entity': 'persona'},
    {'word': 'young girl', 'entity': 'persona'},
    {'word': 'new parent', 'entity': 'persona'},
    {'word': 'dad', 'entity': 'persona'},
    {'word': 'young boy', 'entity': 'persona'},
    {'word': 'an old woman', 'entity': 'persona'},
    {'word': 'baby', 'entity': 'persona'},
    {'word': '20 year vegetarian', 'entity': 'persona'},
    {'word': 'gluten free', 'entity': 'persona'},
    {'word': 'lactose intolerant', 'entity': 'persona'},
    {'word': 'breakfast', 'entity': 'meal'}, 
    {'word': 'lunch', 'entity': 'meal'},
    {'word': 'dinner', 'entity': 'meal'},
    {'word': 'snack', 'entity': 'meal'},
    {'word': 'dessert', 'entity': 'meal'},
    {'word': 'brunch', 'entity': 'meal'},
    {'word': 'party', 'entity': 'meal'},
    {'word': 'appetizer', 'entity':'meal'},
    {'word': 'on-the-go', 'entity': 'occasionConsumption'}, 
    {'word': 'before going to bed', 'entity': 'occasionConsumption'},
    {'word': 'before exercise', 'entity': 'occasionConsumption'},
    {'word': 'business trip', 'entity': 'occasionConsumption'},
    {'word': 'midnight snack', 'entity': 'occasionConsumption'},
    {'word': 'afternoon tea', 'entity': 'occasionConsumption'},
    {'word': 'morning', 'entity': 'occasionTime'}, 
    {'word': 'night', 'entity': 'occasionTime'},
    {'word': 'weekend', 'entity': 'occasionTime'},
    {'word': 'autumn', 'entity': 'occasionTime'},
    {'word': 'afternoon', 'entity': 'occasionTime'},
    {'word': 'winter', 'entity': 'occasionTime'},
    {'word': 'summer', 'entity': 'occasionTime'},
    {'word': 'spring', 'entity': 'occasionTime'},
    {'word': 'evening', 'entity': 'occasionTime'},
    {'word': 'Christmas', 'entity': 'occasionTime'},
    {'word': 'Halloween', 'entity': 'occasionTime'},
    {'word': "new year's eve", 'entity': 'occasionTime'},
]