description_to_entityType = {
    'Company': dict(type='organization', column='name'),
    'Food': dict(type='food', column='name'),
    'Dish': dict(type='food', column='name'),
    'Plants': dict(type='ingredient', column='name'),
    'Drink': dict(type='beverage', column='name'),
    'Cheese': dict(type='ingredient', column='name'),
    'Beverage': dict(type='beverage', column='query'),
    'Fruit': dict(type='ingredient', column='name'),
    'Pasta variety': dict(type='food', column='name'),
    'Cookie': dict(type='food', column='name'),
    'Bread': dict(type='food', column='query'),
    'Restaurant company': dict(type='organization', column='name'),
    'Fish': dict(type='ingredient', column='name'),
    'Animal': dict(type='ingredient', column='query'),
    'Bean': dict(type='ingredient', column='query'),
    'Meat': dict(type='ingredient', column='name'),
    'Food company': dict(type='organization', column='name'),
    'Pasta': dict(type='food', column='query'),
    'Dessert': dict(type='food', column='query'),
    'Vegetable': dict(type='ingredient', column='query'),
    'Type of dish': dict(type='food', column='query'),
    'Supermarket company': dict(type='organization', column='name'),
    'Sauce': dict(type='ingredient', column='query'),
    'Dairy product': dict(type='product', column='query'),
    'Condiment': dict(type='ingredient', column='query'),
    'Fast food restaurant company': dict(type='organization', column='name'),
    'Oil': dict(type='ingredient', column='query'),
    'Spread': dict(type='ingredient', column='name'),
    'Chicken': dict(type='food', column='query'),
    'Tea': dict(type='beverage', column='query'),
    'Soup': dict(type='food', column='query'),
    'Chemical compound': dict(type='ingredient', column='query'),
    'Retail company': dict(type='organization', column='name'),
    'Birds': dict(type='ingredient', column='name'),
    'Nut': dict(type='ingredient', column='name'),
    'Pie': dict(type='food', column='query'),
    'Confection': dict(type='food', column='query'),
    'Fungus': dict(type='ingredient', column='query'),
    'Salad': dict(type='food', column='query'),
    'Corporation': dict(type='organization', column='name'),
    'Spice': dict(type='ingredient', column='name'),
    'Seed': dict(type='ingredient', column='name'),
    'Beef': dict(type='food', column='query'),
    'Cocktail': dict(type='beverage', column='name'),
    'Sausage': dict(type='food', column='query'),
    'Grains': dict(type='ingredient', column='query'),
    'Chocolate bar': dict(type='food', column='query'),
    'Flatbread': dict(type='food', column='query'),
    'Snack': dict(type='food', column='query'),
    'Table sauce': dict(type='ingredient', column='name'),
    'Cake': dict(type='food', column='query'),
    'Soft drink': dict(type='beverage', column='query'),
}

